apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocrandd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocrandd-pod
  template:
    metadata:
      labels:
        app: pocrandd-pod
    spec:
      containers:
      - name: pocrandd
        image: uatacrpocrandd01.azurecr.io/pocrandd:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pocrandd-svc
spec:
  type: NodePort
  selector:
    app: pocrandd-pod
  ports:
  - port: 80
